// static/src/components/Sidebar.jsx
import { Link, useLocation } from 'react-router-dom'
import { FaTimes, FaChartLine, FaHistory, FaCog } from 'react-icons/fa'

const Sidebar = ({ open, toggleSidebar }) => {
  const location = useLocation()
  
  // Navigation items
  const navItems = [
    {
      path: '/',
      name: 'Dashboard',
      icon: <FaChartLine className="w-5 h-5" />
    },
    {
      path: '/history',
      name: 'Signal History',
      icon: <FaHistory className="w-5 h-5" />
    },
    {
      path: '/settings',
      name: 'Settings',
      icon: <FaCog className="w-5 h-5" />
    }
  ]
  
  return (
    <>
      {/* Mobile sidebar backdrop */}
      {open && (
        <div 
          className="fixed inset-0 z-20 bg-black bg-opacity-50 lg:hidden"
          onClick={toggleSidebar}
        />
      )}
      
      {/* Sidebar */}
      <div className={`
        fixed inset-y-0 left-0 z-30 w-64 bg-white dark:bg-gray-800 shadow-lg transform 
        ${open ? 'translate-x-0' : '-translate-x-full'} 
        lg:translate-x-0 lg:static lg:inset-0 
        transition duration-300 ease-in-out
      `}>
        <div className="flex items-center justify-between p-4 border-b dark:border-gray-700">
          <h2 className="text-xl font-bold text-primary dark:text-primary">
            CryptoSignals
          </h2>
          <button 
            onClick={toggleSidebar}
            className="p-1 rounded-md lg:hidden focus:outline-none focus:ring-2 focus:ring-primary"
          >
            <FaTimes className="w-6 h-6 text-gray-600 dark:text-gray-300" />
          </button>
        </div>
        
        <nav className="p-4">
          <ul className="space-y-2">
            {navItems.map((item) => (
              <li key={item.path}>
                <Link
                  to={item.path}
                  className={`
                    flex items-center px-4 py-3 rounded-lg transition-colors duration-200
                    ${location.pathname === item.path 
                      ? 'bg-primary text-white' 
                      : 'text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700'}
                  `}
                  onClick={() => window.innerWidth < 1024 && toggleSidebar()}
                >
                  <span className="mr-3">{item.icon}</span>
                  <span>{item.name}</span>
                </Link>
              </li>
            ))}
          </ul>
        </nav>
        
        <div className="absolute bottom-0 w-full p-4 border-t dark:border-gray-700">
          <div className="text-sm text-gray-500 dark:text-gray-400">
            <p>© 2025 CryptoSignals</p>
            <p>v1.0.0</p>
          </div>
        </div>
      </div>
    </>
  )
}

export default Sidebar

// angular-frontend/src/app/components/sidebar/sidebar.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './sidebar.component.html',
  styleUrls: []
})
export class SidebarComponent {
}
<div class="fixed inset-y-0 left-0 z-50 w-64 bg-white dark:bg-gray-800 shadow-lg">
  <div class="flex h-16 items-center justify-center border-b border-gray-200 dark:border-gray-700">
    <h1 class="text-xl font-bold text-gray-900 dark:text-white">
      <i class="pi pi-chart-line mr-2"></i>
      Coin Signals AI
    </h1>
  </div>
  
  <nav class="mt-8">
    <div class="px-4 space-y-2">
      <a
        routerLink="/dashboard"
        routerLinkActive="bg-blue-50 dark:bg-blue-900 text-blue-700 dark:text-blue-300"
        class="flex items-center px-4 py-3 text-sm font-medium text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
      >
        <i class="pi pi-home mr-3"></i>
        Dashboard
      </a>
      
      <a
        routerLink="/history"
        routerLinkActive="bg-blue-50 dark:bg-blue-900 text-blue-700 dark:text-blue-300"
        class="flex items-center px-4 py-3 text-sm font-medium text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
      >
        <i class="pi pi-history mr-3"></i>
        Történeti kereskedés
      </a>
      
      <a
        routerLink="/portfolio"
        routerLinkActive="bg-blue-50 dark:bg-blue-900 text-blue-700 dark:text-blue-300"
        class="flex items-center px-4 py-3 text-sm font-medium text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
      >
        <i class="pi pi-wallet mr-3"></i>
        Portfólió
      </a>
    </div>
  </nav>
  
  <div class="absolute bottom-4 left-4 right-4">
    <div class="bg-gray-50 dark:bg-gray-700 rounded-lg p-4">
      <div class="flex items-center">
        <div class="w-2 h-2 bg-green-500 rounded-full mr-2"></div>
        <span class="text-xs text-gray-600 dark:text-gray-400">API Connected</span>
      </div>
    </div>
  </div>
</div>
