// static/src/components/TradingViewWidget.jsx
import { useEffect, useRef, memo } from 'react'

const TradingViewWidget = memo(({ symbol = 'BTCUSDT', interval = '1h', theme = 'light' }) => {
  const containerRef = useRef(null)
  const widgetRef = useRef(null)
  
  // Convert interval to TradingView format
  const getIntervalForTradingView = (interval) => {
    switch (interval) {
      case '1m': return '1';
      case '5m': return '5';
      case '15m': return '15';
      case '30m': return '30';
      case '1h': return '60';
      case '4h': return '240';
      case '1d': return 'D';
      case '1w': return 'W';
      default: return '60'; // Default to 1h
    }
  }
  
  useEffect(() => {
    // Clean up previous widget if it exists
    if (widgetRef.current && containerRef.current) {
      containerRef.current.innerHTML = '';
    }
    
    // Skip if TradingView is not available
    if (!window.TradingView) {
      console.error('TradingView library not loaded');
      return;
    }
    
    // Create new widget
    const tradingViewInterval = getIntervalForTradingView(interval);
    
    // Format symbol for TradingView (add BINANCE: prefix)
    const formattedSymbol = `BINANCE:${symbol}`;
    
    widgetRef.current = new window.TradingView.widget({
      container_id: containerRef.current.id,
      autosize: true,
      symbol: formattedSymbol,
      interval: tradingViewInterval,
      timezone: 'Etc/UTC',
      theme: theme === 'dark' ? 'dark' : 'light',
      style: '1',
      locale: 'en',
      toolbar_bg: theme === 'dark' ? '#2A3042' : '#f1f3f6',
      enable_publishing: false,
      hide_top_toolbar: false,
      hide_legend: false,
      save_image: false,
      studies: [
        'RSI@tv-basicstudies',
        'MAExp@tv-basicstudies',
        'MACD@tv-basicstudies',
        'BB@tv-basicstudies'
      ],
      show_popup_button: true,
      popup_width: '1000',
      popup_height: '650',
      withdateranges: true,
    });
    
    return () => {
      // Clean up
      if (widgetRef.current && containerRef.current) {
        containerRef.current.innerHTML = '';
        widgetRef.current = null;
      }
    };
  }, [symbol, interval, theme]);
  
  return (
    <div 
      id="tradingview-widget-container" 
      ref={containerRef} 
      className="w-full h-full min-h-[400px] rounded-lg overflow-hidden"
    />
  );
});

TradingViewWidget.displayName = 'TradingViewWidget';

export default TradingViewWidget;

// angular-frontend/src/app/components/trading-view-widget/trading-view-widget.component.ts
import { Component, Input, OnInit, OnDestroy, OnChanges, ElementRef, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-trading-view-widget',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './trading-view-widget.component.html',
  styleUrls: []
})
export class TradingViewWidgetComponent implements OnInit, OnDestroy, OnChanges {
  @Input() symbol: string = 'BTCUSDT';
  @Input() interval: string = '1h';
  @Input() theme: 'light' | 'dark' = 'light';
  
  @ViewChild('tradingViewContainer', { static: true })
  tradingViewContainer!: ElementRef;

  private widget: any;

  ngOnInit(): void {
    this.loadTradingViewWidget();
  }

  ngOnDestroy(): void {
    if (this.widget) {
      this.widget.remove();
    }
  }

  private loadTradingViewWidget(): void {
    // Load TradingView script if not already loaded
    if (!(window as any).TradingView) {
      const script = document.createElement('script');
      script.src = 'https://s3.tradingview.com/tv.js';
      script.async = true;
      script.onload = () => {
        this.initializeWidget();
      };
      document.head.appendChild(script);
    } else {
      this.initializeWidget();
    }
  }

  private initializeWidget(): void {
    if (this.tradingViewContainer && (window as any).TradingView) {
      // Convert symbol format (BTCUSDT -> BINANCE:BTCUSDT)
      const formattedSymbol = `BINANCE:${this.symbol}`;
      
      this.widget = new (window as any).TradingView.widget({
        autosize: true,
        symbol: formattedSymbol,
        interval: this.interval.toUpperCase(),
        timezone: "Europe/Budapest",
        theme: this.theme,
        style: "1",
        locale: "hu_HU",
        toolbar_bg: "#f1f3f6",
        enable_publishing: false,
        allow_symbol_change: false,
        container_id: this.tradingViewContainer.nativeElement.id,
        studies: [
          "RSI@tv-basicstudies",
          "MACD@tv-basicstudies"
        ],
        show_popup_button: true,
        popup_width: "1000",
        popup_height: "650"
      });
    }
  }

  // Update widget when inputs change
  ngOnChanges(): void {
    if (this.widget) {
      this.widget.remove();
      this.loadTradingViewWidget();
    }
  }
}
<div class="trading-view-widget w-full h-full">
  <div
    #tradingViewContainer
    [id]="'tradingview_' + symbol"
    class="w-full h-full min-h-[320px]"
  >
    <!-- TradingView widget will be loaded here -->
    <div class="flex items-center justify-center h-full bg-gray-100 dark:bg-gray-800 rounded-lg">
      <div class="text-center">
        <i class="pi pi-chart-line text-4xl text-gray-400 mb-4"></i>
        <p class="text-gray-500 dark:text-gray-400">
          Betöltés... {{ symbol }} ({{ interval }})
        </p>
      </div>
    </div>
  </div>
</div>
